/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package src

fun main() {
  // val deriver = Deriver(51.537891, -0.054850)
  // val deriver = Deriver(33.8570583,-118.2477304)
  val deriver = Deriver(48.8556945,2.3369408)

  try {
    while (true) deriver.walk()
  } catch (e: Exception) {
    println(e.toString())
    deriver.finish()
  }
}
